version: "3.2"
services:

  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql
      - ./database_dumps:/var/opt/mssql/backup
    environment:
      SA_PASSWORD: "Strong.Password.01"
      ACCEPT_EULA: "Y"

volumes:
  db_data: {}